export const ACTION_TYPES = {
  GET_COVID_DATA_PENDING: "GET_COVID_DATA_PENDING",
  GET_COVID_DATA_FAILURE: "GET_COVID_DATA_FAILURE",
  GET_COVID_DATA_SUCCESSFUL: "GET_COVID_DATA_SUCCESSFUL",
  GET_VACCINE_DATA_PENDING: "GET_VACCINE_DATA_PENDING",
  GET_VACCINE_DATA_FAILURE: "GET_VACCINE_DATA_FAILURE",
  GET_VACCINE_DATA_SUCCESSFUL: "GET_VACCINE_DATA_SUCCESSFUL",
};
